// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xbjkwcqebpguojyljfvq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhiamt3Y3FlYnBndW9qeWxqZnZxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY0NTAyOTcsImV4cCI6MjA2MjAyNjI5N30.nmKXbK292K8Ez1XicMp9fpI_pGE0Cg5WFBPUX3pMoO0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);